import { getSession, logout } from "lib";
import { Inter } from "next/font/google";
import Logout from "~/components/logout";
import "~/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} bg-[#faebd7]`}>
        <header
          className={`font-sans ${inter.variable} bg-white p-4 text-center`}
        >
          THIS IS A HEADER {session && <Logout logout={logout} />}
        </header>
        {children}
      </body>
    </html>
  );
}
